apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-python-chart.fullname" . }}
  labels:
    {{- include "app-python-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app-python-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app-python-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: SECRET_VALUE
              valueFrom:
                secretKeyRef:
                  name: app-python-secret
                  key: secretValue
          resources:
            limits:
              cpu: 1
              memory: 200M
            requests:
              cpu: 200m
              memory: 10M
