apiVersion: v1
kind: Secret
metadata:
  name: app-python-secret
  labels:
    {{- include "app-python-chart.labels" . | nindent 4 }}
type: Opaque
data:
  secretValue: {{ .Values.secretValue | b64enc | quote }}
