apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-python
  labels:
    app: moscow-time

spec:
  replicas: 3
  selector:
    matchLabels:
      app: moscow-time-ts
  template:
    metadata:
      labels:
        app: moscow-time-ts
    spec: 
      containers:
        - name: app-ts
          image: illright/devops_lab1_ts:1.0.1
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service

metadata:
  name: app-ts-service

spec:
  selector:
    app: moscow-time-ts
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000 
