- name: Install Docker and Docker Compose
  hosts: all
  remote_user: ubuntu
  roles:
    - role: geerlingguy.docker
      vars:
        docker_package_state: present
        docker_service_state: started
        docker_service_enabled: yes
        docker_install_compose: yes
        docker_compose_version: "1.29.2"
      become: yes
