- name: Create the application directory
  ansible.builtin.file:
    path: "{{ app_path }}"
    state: directory
    mode: a+rw

- name: Copy over the Docker Compose configuration
  ansible.builtin.copy:
    src: "{{ docker_compose_path }}"
    dest: "{{ app_path }}/docker-compose.yaml"
    mode: preserve
